sudo: no

language: python

env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27-1.8
  - TOXENV=py27-1.9
  - TOXENV=py27-1.10
  - TOXENV=py27-1.11
  - TOXENV=py33-1.8
  - TOXENV=py34-1.8
  - TOXENV=py34-1.9
  - TOXENV=py34-1.10
  - TOXENV=py34-1.11
  - TOXENV=py34-master

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35-1.9
    - python: 3.5
      env: TOXENV=py35-1.10
    - python: 3.5
      env: TOXENV=py35-1.11
    - python: 3.5
      env: TOXENV=py35-master
    - python: 3.6
      env: TOXENV=py36-master
  allow_failures:
    - env: TOXENV=py34-master
    - env: TOXENV=py35-master
    - env: TOXENV=py36-master

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - if [ -f .coverage ]; then coveralls; fi
