sudo: no

language: python

env:
  - TOXENV=flake8
  - TOXENV=isort
  - TOXENV=py27-1.7
  - TOXENV=py27-1.8
  - TOXENV=py27-master
  - TOXENV=py32-1.7
  - TOXENV=py32-1.8
  - TOXENV=py33-1.7
  - TOXENV=py33-1.8
  - TOXENV=py33-master
  - TOXENV=py34-1.7
  - TOXENV=py34-1.8
  - TOXENV=py34-master

matrix:
  allow_failures:
    - env: TOXENV=py27-master
    - env: TOXENV=py33-master
    - env: TOXENV=py34-master

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - if [ -f .coverage ]; then coveralls; fi
