language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="https://github.com/django/django/tarball/master"

matrix:
  allow_failures:
    - env: DJANGO="https://github.com/django/django/tarball/master"

install:
  - pip install $DJANGO argparse --use-mirrors

script:
  - python runtests.py
